pdf_host_name: localhost:3000
use_https: false
delayed_wrap_up: false
from_address: "rocky-dev@gmail.com"
default_url_host: "register.example.com"

hours_before_first_reminder: 0.0333
hours_between_first_and_second_reminder: 0.0333
pdf_expiration_days: .25

states_with_online_registration:
  - AZ
  - CA
  - CO
  - NV
  - WA
