pdf_host_name: localhost:3001
api_host_name: http://localhost:3001
use_https: false
from_address: "rocky-dev@gmail.com"
default_url_host: "register.example.com"
ui_url_host: "localhost:3000"

hours_before_first_reminder: 0.0333
hours_between_first_and_second_reminder: 0.0333
hours_between_second_and_final_reminder: 0.0333
pdf_expiration_days: .25

ovr_states:
  CA:
    api_settings:
      debug_in_ui: true
      log_all_requests: true
      disclosures_font_size: 14px
      disclosures_box_height: 100px
      disclosures_prechecked: true
  NV:
    redirect_to_online_url: true
    languages:
      - en
      - es
  WA:
    languages:
      - en
      - es
  

states_with_online_registration:
  - CA
  - AZ
  - CO
  - NV
  - WA
  
enabled_locales:
  - en
  - es
  - ko
  - tl
  - ilo
  - hi
  - km
  - th
  - vi
  - zh
  - zh-tw
  - ja