pdf_host_name: 'register.rockthevote.com'
from_address: "register@rockthevote.com"
default_url_host: "register.rockthevote.com"


states_with_online_registration:
  - CA
  - NV
  - WA

ovr_states:
  CA:
    - en
    - es
  NV:
    - en
  WA:
    - en

enabled_locales:
  - en
  - es
  - ko