pdf_host_name: 'rtvstaging2.osuosl.org'
from_address:  "register@rockthevote.com"
default_url_host: "rtvstaging2.osuosl.org"

hours_before_first_reminder: 0.0333
hours_between_first_and_second_reminder: 0.0333
pdf_expiration_days: .25
admin_password: abc123

states_with_online_registration:
  - CA
  - NV
  - WA


ovr_states:
  CA:
    api_settings:
      debug_in_ui: true
      log_all_requests: true
      disclosures_font_size: 12px
      disclosures_box_height: 170px
  NV:
    languages:
      - en
      - es

enabled_locales:
  - en
  - es
  - ko
  - tl
  - ilo
  - hi
  - km
  - th
  - vi
  - zh
  - ja
  - zh-tw
  - ur
  - bn

pdf:
  pdf_gen_server: "http://rtvstaging-pdforg1.osuosl.org"
