pdf_host_name: 'rtvstaging.osuosl.org'
from_address:  "register@rockthevote.com"
default_url_host: "rtvstaging.osuosl.org"



hours_before_first_reminder: 0.0333
hours_between_first_and_second_reminder: 0.0333
pdf_expiration_days: .25

enabled_locales:
  - en
  - es
  - ko