pdf_host_name: 'example-pdf.com'
api_host_name: 'http://example-api.com'
use_https: false
paperclip_options:
  path: ":rails_root/tmp/system/:attachment/:id/:style/:filename"
  
  
hours_before_first_reminder: 0.0333
hours_between_first_and_second_reminder: 0.0333
pdf_expiration_days: .25

states_with_online_registration:
  - AZ
  - CA
  - CO
  - NV
  - WA
  
enabled_locales:
  - en
  - es
  - ko
  - zh-tw

ovr_states:
  CA:
    languages:
      - en
      - es
      - ko
  NV:
    languages:
      - en
  WA:
    languages:
      - en
      - es

